version: 1
disable_existing_loggers: True

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s]: <PID:%(process)s Thread:%(threadName)s> %(name)s %(pathname)s %(funcName)s line:%(lineno)d - %(message)s"
  error:
    format: "%(asctime)s [%(levelname)s]: <PID:%(process)s Thread:%(threadName)s> %(name)s %(pathname)s %(funcName)s line:%(lineno)d - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/cf2py.log # XXX logs should be mounted volume
    maxBytes: 10485760 # 10MB
    backupCount: 30
    encoding: utf8

loggers:
  cf2py-logger:
    level: INFO
    handlers: []
    propogate: yes

root:
  level: NOTSET
  handlers: [console_handler, file_handler]
  propogate: yes
